server:
  port: 9900
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pzy2019/java1907.git

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
    registry-fetch-interval-seconds: 30